export const TYPES = {
  Application: Symbol.for('Application'),
  ILogger: Symbol.for('ILogger'),
  UserService: Symbol.for('UserService'),
  UserController: Symbol.for('UserController'),
  ProductController: Symbol.for('ProductController'),
  ShoppingCartController: Symbol.for('ShoppingCartController'),
  ShoppingCartService: Symbol.for('ShoppingCartService'),
  FavouriteService: Symbol.for('FavouriteService'),
  FavouritesController: Symbol.for('FavouritesController'),
  SequelizeService: Symbol('SequelizeService'),
  ExceptionFilter: Symbol.for('ExceptionFilter'),
  ConfigService: Symbol.for('ConfigService'),
  UsersRepository: Symbol.for('UsersRepository'),
};
